// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class UniswapFactory {
  static entity = "UniswapFactory";
  static schema = {
    id: "String",
    pairCount: "String",
    totalVolumeUSD: "String",
    totalVolumeETH: "String",
    untrackedVolumeUSD: "String",
    totalLiquidityUSD: "String",
    totalLiquidityETH: "String",
    txCount: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Token {
  static entity = "Token";
  static schema = {
    id: "String",
    tradeVolume: "String",
    tradeVolumeUSD: "String",
    untrackedVolumeUSD: "String",
    txCount: "String",
    totalLiquidity: "String",
    derivedETH: "String",
    tokenDayData: ["String"],
    pairDayDataBase: ["String"],
    pairDayDataQuote: ["String"],
    pairBase: ["String"],
    pairQuote: ["String"],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Pair {
  static entity = "Pair";
  static schema = {
    id: "String",
    token0: "String",
    token1: "String",
    reserve0: "String",
    reserve1: "String",
    totalSupply: "String",
    reserveETH: "String",
    reserveUSD: "String",
    trackedReserveETH: "String",
    token0Price: "String",
    token1Price: "String",
    volumeToken0: "String",
    volumeToken1: "String",
    volumeUSD: "String",
    untrackedVolumeUSD: "String",
    txCount: "String",
    createdAtTimestamp: "String",
    createdAtBlockNumber: "Number",
    liquidityProviderCount: "String",
    pairHourData: ["String"],
    liquidityPositions: ["String"],
    liquidityPositionSnapshots: ["String"],
    mints: ["String"],
    burns: ["String"],
    swaps: ["String"],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Bundle {
  static entity = "Bundle";
  static schema = {
    id: "String",
    ethPrice: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

import { String, Array, Number } from "@blockflow-labs/utils";

export interface IUniswapFactory extends Document {
  id: String;
  pairCount: String;
  totalVolumeUSD: String;
  totalVolumeETH: String;
  untrackedVolumeUSD: String;
  totalLiquidityUSD: String;
  totalLiquidityETH: String;
  txCount: String;
  blocknumber: String;
  entityId: String;
}

export interface IToken extends Document {
  id: String;
  // symbol: String;
  // name: String;
  // decimals: String;
  // totalSupply: String;
  tradeVolume: String;
  tradeVolumeUSD: String;
  untrackedVolumeUSD: String;
  txCount: String;
  totalLiquidity: String;
  derivedETH: String;
  tokenDayData: [String];
  pairDayDataBase: [String];
  pairDayDataQuote: [String];
  pairBase: [String];
  pairQuote: [String];
  blocknumber: String;
  entityId: String;
}

export interface IPair extends Document {
  id: String;

  token0: String;
  token1: String;
  reserve0: String;
  reserve1: String;
  totalSupply: String;

  reserveETH: String;
  reserveUSD: String;
  trackedReserveETH: String;

  token0Price: String;
  token1Price: String;

  volumeToken0: String;
  volumeToken1: String;
  volumeUSD: String;
  untrackedVolumeUSD: String;
  txCount: String;

  createdAtTimestamp: String;
  createdAtBlockNumber: Number;

  liquidityProviderCount: String;
  pairHourData: [String];
  liquidityPositions: [String];
  liquidityPositionSnapshots: [String];
  mints: [String];
  burns: [String];
  swaps: [String];
  blocknumber: String;
  entityId: String;
}

export interface IBundle extends Document {
  id: String;
  ethPrice: String;
  blocknumber: String;
  entityId: String;
}
