const transactionSchema = [
  { name: "src_timestamp", type: "Number" },
  { name: "dest_timestamp", type: "Number" },
  { name: "src_block_number", type: "Number" },
  { name: "dest_block_number", type: "Number" },
  { name: "src_chain_id", type: "String" },
  { name: "dest_chain_id", type: "String" },
  { name: "src_chain_type", type: "String" },
  { name: "dest_chain_type", type: "String" },
  { name: "src_tx_hash", type: "String" },
  { name: "dest_tx_hash", type: "String" },
  { name: "status", type: "String" },
  { name: "src_address", type: "String" },
  { name: "dest_address", type: "String" },
  { name: "src_amount", type: "String" },
  { name: "dest_amount", type: "String" },
  { name: "src_symbol", type: "String" },
  { name: "dest_symbol", type: "String" },
  { name: "fee_amount", type: "String" },
  { name: "fee_address", type: "String" },
  { name: "fee_symbol", type: "String" },
  { name: "src_stable_symbol", type: "String" },
  { name: "src_stable_address", type: "String" },
  { name: "src_stable_amount", type: "String" },
  { name: "dest_stable_symbol", type: "String" },
  { name: "dest_stable_address", type: "String" },
  { name: "dest_stable_amount", type: "String" },
  { name: "usdc_value", type: "String" },
  { name: "depositor_address", type: "String" },
  { name: "sender_address", type: "String" },
  { name: "receiver_address", type: "String" },
  { name: "recipient_address", type: "String" },
  { name: "deposit_id", type: "String" },
  { name: "forwarder_address", type: "String" },
  { name: "message_hash", type: "String" },
  { name: "has_message", type: "Boolean" },
  { name: "message", type: "String" },
  { name: "update_tx_hash", type: "String" },
  { name: "refund_outbound_id", type: "String" },
  { name: "fund_paid_confirmed", type: "Boolean" },
  { name: "deposit_info_type", type: "String" },
  { name: "flow_type", type: "String" },
  { name: "gas_fee_usd", type: "String" },
  { name: "bridge_fee_usd", type: "String" },
  { name: "competitor_data", type: "CompetitorData" },
  { name: "src_partial_info", type: "Boolean" },
  { name: "dest_partial_info", type: "Boolean" },
  { name: "widget_id", type: "String" },
  { name: "native_token_amount", type: "String" },
  { name: "native_token_symbol", type: "String" },
  { name: "sys_fee", type: "String" },
  { name: "partner_fee", type: "String" },
  { name: "forwarder_fee", type: "String" },
  { name: "expiry_timestamp", type: "Number" },
  { name: "execFlag", type: "Boolean" },
  { name: "execData", type: "String" },
];

export const nitroSchema = {
  findNitroTransactionsByFilter: transactionSchema,
  findNitroTransactionByFilter: transactionSchema,
};
