// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class burnTransactionsTable {
  static entity = "burnTransactionsTable";
  static schema = {
    id: { type: "String", index: true },
    transactionHash: "string",
    sourceDomain: "string",
    destinationDomain: "string",
    amount: "number",
    mintRecipient: "string",
    messageSender: "string",
    timeStamp: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class mintTransactionsTable {
  static entity = "mintTransactionsTable";
  static schema = {
    id: { type: "String", index: true },
    transactionHash: "string",
    sourceDomain: "string",
    destinationDomain: "string",
    amount: "number",
    mintRecipient: "string",
    timeStamp: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class attestationTable {
  static entity = "attestationTable";
  static schema = {
    id: { type: "String", index: true },
    attestationHash: "string",
    messageHash: "string",
    timeStamp: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class DomainsTable {
  static entity = "DomainsTable";
  static schema = {
    id: { type: "String", index: true },
    domainName: "string",
    chainId: { type: "String", index: true },
    tokenAddress: "string",
    permessageburnlimit: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class FeeInfo {
  static entity = "FeeInfo";
  static schema = {
    id: { type: "String", index: true },
    feeInUSDC: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class cctpDayDataDB {
  static entity = "cctpDayDataDB";
  static schema = {
    id: { type: "String", index: true },
    date: "string",
    txCount: "string",
    dailyVolume: "string",
    deposited: "string",
    withdrawal: "string",
    totalFee: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class cctpWeekDataDB {
  static entity = "cctpWeekDataDB";
  static schema = {
    id: { type: "String", index: true },
    week: "string",
    txCount: "string",
    weeklyVolume: "string",
    deposited: "string",
    withdrawal: "string",
    totalFee: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class cctpMonthDataDB {
  static entity = "cctpMonthDataDB";
  static schema = {
    id: { type: "String", index: true },
    month: "string",
    txCount: "string",
    monthlyVolume: "string",
    deposited: "string",
    withdrawal: "string",
    totalFee: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class cctpYearDataDB {
  static entity = "cctpYearDataDB";
  static schema = {
    id: { type: "String", index: true },
    year: "string",
    txCount: "string",
    yearlyVolume: "string",
    deposited: "string",
    withdrawal: "string",
    totalFee: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class cctpAllTimeDB {
  static entity = "cctpAllTimeDB";
  static schema = {
    id: { type: "String", index: true },
    txCount: "string",
    allTimeVolume: "string",
    deposited: "string",
    withdrawal: "string",
    totalFee: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

import { String, Array } from "@blockflow-labs/utils";

export interface IburnTransactionsTable extends Document {
  id: String;
  transactionHash: string;
  sourceDomain: string;
  destinationDomain: string;
  amount: number;
  mintRecipient: string;
  messageSender: string;
  timeStamp: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface ImintTransactionsTable extends Document {
  id: String;
  transactionHash: string;
  sourceDomain: string;
  destinationDomain: string;
  amount: number;
  mintRecipient: string;
  timeStamp: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IattestationTable extends Document {
  id: String;
  attestationHash: string;
  messageHash: string;
  timeStamp: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IDomainsTable extends Document {
  id: String;
  domainName: string;
  chainId: string;
  tokenAddress: string;
  permessageburnlimit: number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
}

export interface IFeeInfo extends Document {
  id: String;
  feeInUSDC: number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IcctpDayDataDB extends Document {
  id: String; // chainId_date
  date: string;
  txCount: string;
  dailyVolume: string; // summation of deposited and withdrawl
  deposited: string; // messageReceived
  withdrawal: string; // depositForBurn
  totalFee: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IcctpWeekDataDB extends Document {
  id: String; // chainId_week -> week since epoch
  week: string;
  txCount: string;
  weeklyVolume: string;
  deposited: string;
  withdrawal: string;
  totalFee: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IcctpMonthDataDB extends Document {
  id: String;
  month: string;
  txCount: string;
  monthlyVolume: string;
  deposited: string;
  withdrawal: string;
  totalFee: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IcctpYearDataDB extends Document {
  id: String;
  year: string;
  txCount: string;
  yearlyVolume: string;
  deposited: string;
  withdrawal: string;
  totalFee: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IcctpAllTimeDB extends Document {
  id: String;
  txCount: string;
  allTimeVolume: string;
  deposited: string;
  withdrawal: string;
  totalFee: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
