// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class Staker {
  static entity = "Staker";
  static schema = {
    id: { type: "String", index: true },
    address: "string",
    operator: "string",
    shares: [{ strategy: "string", shares: "string" }],
    createdAt: "Number",
    updatedAt: "Number",
    createdAtBlock: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Operator {
  static entity = "Operator";
  static schema = {
    id: { type: "String", index: true },
    address: "string",
    avsRegistrations: [{ address: "string", isActive: "Boolean" }],
    metadataURI: "string",
    shares: [{ strategy: "string", shares: "string" }],
    createdAt: "Number",
    updatedAt: "Number",
    createdAtBlock: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class AVS {
  static entity = "AVS";
  static schema = {
    id: { type: "String", index: true },
    address: "string",
    metadataURI: "string",
    operators: ["string"],
    createdAt: "Number",
    updatedAt: "Number",
    createdAtBlock: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Withdrawal {
  static entity = "Withdrawal";
  static schema = {
    id: { type: "String", index: true },
    withdrawalRoot: "string",
    nonce: "Number",
    stakerAddress: "string",
    delegatedTo: "string",
    withdrawerAddress: "string",
    strategyShares: [{ strategy: "string", shares: "string" }],
    isCompleted: "Boolean",
    createdAt: "Number",
    createdAtBlock: "Number",
    updatedAt: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Deposit {
  static entity = "Deposit";
  static schema = {
    id: { type: "String", index: true },
    transactionHash: "string",
    stakerAddress: "string",
    tokenAddress: "string",
    strategyAddress: "string",
    shares: "string",
    createdAt: "Number",
    createdAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class EigenPod {
  static entity = "EigenPod";
  static schema = {
    id: { type: "String", index: true },
    address: "string",
    owner: "string",
    createdAt: "Number",
    createdAtBlock: "Number",
    updatedAt: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class PodTransactions {
  static entity = "PodTransactions";
  static schema = {
    id: { type: "String", index: true },
    podAddress: "string",
    podOwner: "string",
    transactionHash: "string",
    transactionIndex: "Number",
    createdAt: "Number",
    createdAtBlock: "Number",
    updatedAt: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Strategies {
  static entity = "Strategies";
  static schema = {
    id: { type: "String", index: true },
    address: "string",
    symbol: "string",
    sharesToUnderlying: "string",
    totalShares: "string",
    createdAt: "Number",
    createdAtBlock: "Number",
    updatedAt: "Number",
    updatedAtBlock: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export type StrategyShares = {
  strategy: string;
  shares: string;
};

export type AVSRegistrations = {
  address: string;
  isActive: Boolean;
};

export interface IStaker extends Document {
  id: string;
  address: string;
  operator: string;
  shares: [StrategyShares];
  createdAt: Number;
  updatedAt: Number;
  createdAtBlock: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IOperator extends Document {
  id: string;
  address: string;
  avsRegistrations: [AVSRegistrations];
  metadataURI: string;
  shares: [StrategyShares];
  createdAt: Number;
  updatedAt: Number;
  createdAtBlock: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IAVS extends Document {
  id: string;
  address: string;
  metadataURI: string;
  operators: [string];
  createdAt: Number;
  updatedAt: Number;
  createdAtBlock: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IWithdrawal extends Document {
  id: string;
  withdrawalRoot: string;
  nonce: Number;
  stakerAddress: string;
  delegatedTo: string;
  withdrawerAddress: string;
  strategyShares: [StrategyShares];
  isCompleted: Boolean;
  createdAt: Number;
  createdAtBlock: Number;
  updatedAt: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IDeposit extends Document {
  id: string;
  transactionHash: string;
  stakerAddress: string;
  tokenAddress: string;
  strategyAddress: string;
  shares: string;
  createdAt: Number;
  createdAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IEigenPod extends Document {
  id: string;
  address: string;
  owner: string;

  createdAt: Number;
  createdAtBlock: Number;
  updatedAt: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IPodTransactions extends Document {
  id: string;
  podAddress: string;
  podOwner: string;
  transactionHash: string;
  transactionIndex: Number;

  createdAt: Number;
  createdAtBlock: Number;
  updatedAt: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IStrategies extends Document {
  id: string;
  address: string;
  symbol: string;
  sharesToUnderlying: string;
  totalShares: string;

  createdAt: Number;
  createdAtBlock: Number;
  updatedAt: Number;
  updatedAtBlock: Number;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
