// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class TradeData {
  static entity = "TradeData";
  static schema = {
    id: { type: "String", index: true },
    protocolAddress: "string",
    owner: "string",
    sellToken: "string",
    buyToken: "string",
    sellAmount: "string",
    buyAmount: "string",
    solver: "string",
    feeAmount: "string",
    orderUid: "string",
    timeStamp: "string",
    transactionHash: "string",
    gasUsed: "string",
    gasCost: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class SolverData {
  static entity = "SolverData";
  static schema = {
    id: { type: "String", index: true },
    solverAddress: "string",
    totalTransactions: "string",
    totalVolume: "string",
    averageVolume: "string",
    totalGasUsed: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class LiqudityData {
  static entity = "LiqudityData";
  static schema = {
    id: { type: "String", index: true },
    target: "string",
    value: "string",
    selector: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class BridgeData {
  static entity = "BridgeData";
  static schema = {
    id: { type: "String", index: true },
    transactionHashSrc: "string",
    transactionHashDest: "string",
    from: "string",
    fromValue: "string",
    to: "string",
    toValue: "string",
    solver: "string",
    solverGasCost: "string",
    timestampSrc: "string",
    timestampDest: "string",
    bridgeTime: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

import { String } from "@blockflow-labs/utils";

export interface ITradeData extends Document {
  id: String;
  protocolAddress: string;
  owner: string;
  sellToken: string;
  buyToken: string;
  sellAmount: string;
  buyAmount: string;
  solver: string;
  feeAmount: string;
  orderUid: string;
  timeStamp: string;
  transactionHash: string;
  gasUsed: string;
  gasCost: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface ISolverData extends Document {
  id: String;
  solverAddress: string;
  totalTransactions: string;
  totalVolume: string;
  averageVolume: string;
  totalGasUsed: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface ILiqudityData extends Document {
  id: String;
  target: string;
  value: string;
  selector: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IBridgeData extends Document {
  id: String;
  transactionHashSrc: string;
  transactionHashDest: string;
  from: string;
  fromValue: string;
  to: string;
  toValue: string;
  solver: string;
  solverGasCost: string;
  timestampSrc: string;
  timestampDest: string;
  bridgeTime: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
