// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export class Transaction {
  static entity = "Transaction";
  static schema = {
    id: "string",
    transactionHash: "string",
    userOpHashes: ["string"],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Block {
  static entity = "Block";
  static schema = {
    id: "string",
    transactionHashesWithUserOps: ["string"],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class AccountFactory {
  static entity = "AccountFactory";
  static schema = {
    id: "String",
    totalAccount: "Number",
    accounts: ["String"],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Account {
  static entity = "Account";
  static schema = {
    id: "String",
    ops: ["String"],
    paymaster: "String",
    createdAt: "String",
    updatedAt: "String",
    createdHash: "String",
    createdOpHash: "String",
    totalOperations: "String",
    factory: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Blockchain {
  static entity = "Blockchain";
  static schema = {
    id: "String",
    totalAccount: "String",
    totalOperations: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Paymaster {
  static entity = "Paymaster";
  static schema = {
    id: "String",
    ops: ["String"],
    createdAt: "String",
    updatedAt: "String",
    totalOperations: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Bundler {
  static entity = "Bundler";
  static schema = {
    id: "String",
    ops: ["String"],
    createdAt: "String",
    updatedAt: "String",
    totalOperations: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class UserOperationRevertReason {
  static entity = "UserOperationRevertReason";
  static schema = {
    id: "String",
    sender: "String",
    nonce: "Number",
    reason: "String",
    txHash: "String",
    block: "String",
    createdAt: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class UserOperation {
  static entity = "UserOperation";
  static schema = {
    id: "String",
    txHash: "String",
    block: "String",
    bundler: "String",
    sender: "String",
    paymaster: "String",
    nonce: "Number",
    success: "Boolean",
    actualGasCost: "Number",
    actualGasUsed: "Number",
    createdAt: "String",
    initCode: "string",
    callData: "string",
    callGasLimit: "string",
    verificationGasLimit: "string",
    preVerificationGas: "string",
    maxFeePerGas: "string",
    maxPriorityFeePerGas: "string",
    paymasterAndData: "string",
    signature: "string",
    beneficiary: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}
