// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export class UserOp {
  static entity = "UserOp";
  static entityId = "eb4b0072-b7ad-4a59-b8b8-457ce84e0afe";
  static schema = {
    id: "string",
    userOpHash: "string",
    sender: "string",
    nonce: "string",
    initCode: "string",
    callData: "string",
    callGasLimit: "string",
    verificationGasLimit: "string",
    preVerificationGas: "string",
    maxFeePerGas: "string",
    maxPriorityFeePerGas: "string",
    paymasterAndData: "string",
    signature: "string",
    beneficiary: "string",
    transactionHash: "string",
    blockNumber: "string",
    blockTimeStamp: "string",
    entryPoint: "string",
    entityId: "String",
    blocknumber: { type: "String", index: true },
  };

  static async save(data: any, callback: Function): Promise<void> {
    data.entityId = UserOp.entityId;
    await callback(UserOp.entity, UserOp.schema, data);
  }

  static async load(id: string, callback: Function): Promise<any> {
    const res = await callback(UserOp.entity, UserOp.schema, id);
    res.id = id;
    return res;
  }

  static async bind(): Promise<UserOp> {
    return new UserOp();
  }
}

export class Transaction {
  static entity = "Transaction";
  static entityId = "d6d415c7-1249-42f6-b2e6-c8a005e277a6";
  static schema = {
    id: "string",
    transactionHash: "string",
    userOpHashes: "string[]",
    entityId: "String",
    blocknumber: { type: "String", index: true },
  };

  static async save(data: any, callback: Function): Promise<void> {
    data.entityId = Transaction.entityId;
    await callback(Transaction.entity, Transaction.schema, data);
  }

  static async load(id: string, callback: Function): Promise<any> {
    const res = await callback(Transaction.entity, Transaction.schema, id);
    res.id = id;
    return res;
  }

  static async bind(): Promise<Transaction> {
    return new Transaction();
  }
}

export class Block {
  static entity = "Block";
  static entityId = "5482a932-933e-457b-b504-ddfc3b2faa99";
  static schema = {
    id: "string",
    blockNumber: "string",
    transactionHashesWithUserOps: "string[]",
    entityId: "String",
    blocknumber: { type: "String", index: true },
  };

  static async save(data: any, callback: Function): Promise<void> {
    data.entityId = Block.entityId;
    await callback(Block.entity, Block.schema, data);
  }

  static async load(id: string, callback: Function): Promise<any> {
    const res = await callback(Block.entity, Block.schema, id);
    res.id = id;
    return res;
  }

  static async bind(): Promise<Block> {
    return new Block();
  }
}
