// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class UniIncentive {
  static entity = "UniIncentive";
  static schema = {
    id: { type: "String", index: true },
    rewardToken: "String",
    pool: "String",
    startTime: "number",
    endTime: "number",
    refundee: "String",
    reward: "String",
    ended: "Boolean",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class UniPosition {
  static entity = "UniPosition";
  static schema = {
    id: { type: "String", index: true },
    tokenId: "number",
    owner: "String",
    liquidity: "String",
    staked: "Boolean",
    oldOwner: "String",
    approved: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class UniReward {
  static entity = "UniReward";
  static schema = {
    id: { type: "String", index: true },
    recipient: "String",
    rewardToken: "String",
    reward: "String",
    rewardRecipientAddress: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

import { String } from "@blockflow-labs/utils";

export interface IUniIncentive extends Document {
  id: String;
  rewardToken: String;
  pool: String;
  startTime: number;
  endTime: number;
  refundee: String;
  reward: String;
  ended: Boolean;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IUniPosition extends Document {
  id: String;
  tokenId: number;
  owner: String;
  liquidity: String;
  staked: Boolean;
  oldOwner: String;
  approved: String;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IUniReward extends Document {
  id: String;
  recipient: String;
  rewardToken: String;
  reward: String;
  rewardRecipientAddress: String;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
