// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils"

export class User {
  static entity = "User"
  static schema = {
    id: { type: "String", index: true },
    tokenBalance: "number",
    vaultBalance: "number",
    entryValue: "number",
    realizedEarnings: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class Token {
  static entity = "Token"
  static schema = {
    id: { type: "String", index: true },
    name: "string",
    totalSupply: "number",
    multiplier: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class Vault {
  static entity = "Vault"
  static schema = {
    id: { type: "String", index: true },
    name: "string",
    vaultAddress: "string",
    totalSupply: "number",
    totalHolding: "number",
    pricePerShare: "number",
    totalTokenEarnings: "number",
    minimumLock: "number",
    peripheryAddress: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class dailyUserTrack {
  static entity = "dailyUserTrack"
  static schema = {
    id: { type: "String", index: true },
    userId: "String",
    dailyVaultBalance: "number",
    dailyEntryValue: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class monthlyUserTrack {
  static entity = "monthlyUserTrack"
  static schema = {
    id: { type: "String", index: true },
    userId: "String",
    monthlyVaultBalance: "number",
    monthlyEntryValue: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class yearlyUserTrack {
  static entity = "yearlyUserTrack"
  static schema = {
    id: { type: "String", index: true },
    userId: "String",
    yearlyVaultBalance: "number",
    yearlyEntryValue: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class dailyVolume {
  static entity = "dailyVolume"
  static schema = {
    id: { type: "String", index: true },
    dailyVaultTotalSupply: "number",
    dailyPricePerShare: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class monthlyVolume {
  static entity = "monthlyVolume"
  static schema = {
    id: { type: "String", index: true },
    monthlyVaultTotalSupply: "number",
    monthlyPricePerShare: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class yearlyVolume {
  static entity = "yearlyVolume"
  static schema = {
    id: { type: "String", index: true },
    yearlyVaultTotalSupply: "number",
    yearlyPricePerShare: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class dailyAPY {
  static entity = "dailyAPY"
  static schema = {
    id: { type: "String", index: true },
    dailyTokenEarnings: "number",
    averageTokenEarningsPerToken: "number",
    dailyAPYamount: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class weeklyAPY {
  static entity = "weeklyAPY"
  static schema = {
    id: { type: "String", index: true },
    weeklyTokenEarnings: "number",
    averageTokenEarningsPerToken: "number",
    weeklyAPYamount: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class monthlyAPY {
  static entity = "monthlyAPY"
  static schema = {
    id: { type: "String", index: true },
    monthlyTokenEarnings: "number",
    averageTokenEarningsPerToken: "number",
    monthlyAPYamount: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

export class yearlyAPY {
  static entity = "yearlyAPY"
  static schema = {
    id: { type: "String", index: true },
    yearlyTokenEarnings: "number",
    averageTokenEarningsPerToken: "number",
    yearlyAPYamount: "number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  }
}

import { String, Array } from "@blockflow-labs/utils"

export interface IUser extends Document {
  id: String
  tokenBalance: number
  vaultBalance: number
  entryValue: number
  realizedEarnings: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IToken extends Document {
  id: String
  name: string
  totalSupply: number
  multiplier: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IVault extends Document {
  id: String
  name: string
  vaultAddress: string
  totalSupply: number
  totalHolding: number
  pricePerShare: number
  totalTokenEarnings: number
  minimumLock: number
  peripheryAddress: string
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IdailyUserTrack extends Document {
  id: String
  userId: String
  dailyVaultBalance: number
  dailyEntryValue: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface ImonthlyUserTrack extends Document {
  id: String
  userId: String
  monthlyVaultBalance: number
  monthlyEntryValue: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IyearlyUserTrack extends Document {
  id: String
  userId: String
  yearlyVaultBalance: number
  yearlyEntryValue: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IdailyVolume extends Document {
  id: String
  dailyVaultTotalSupply: number
  dailyPricePerShare: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface ImonthlyVolume extends Document {
  id: String
  monthlyVaultTotalSupply: number
  monthlyPricePerShare: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IyearlyVolume extends Document {
  id: String
  yearlyVaultTotalSupply: number
  yearlyPricePerShare: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IdailyAPY extends Document {
  id: String
  dailyTokenEarnings: number
  averageTokenEarningsPerToken: number
  dailyAPYamount: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IweeklyAPY extends Document {
  id: String
  weeklyTokenEarnings: number
  averageTokenEarningsPerToken: number
  weeklyAPYamount: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface ImonthlyAPY extends Document {
  id: String
  monthlyTokenEarnings: number
  averageTokenEarningsPerToken: number
  monthlyAPYamount: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}

export interface IyearlyAPY extends Document {
  id: String
  yearlyTokenEarnings: number
  averageTokenEarningsPerToken: number
  yearlyAPYamount: number
  blocknumber: String
  entityId: String
  instanceId: String
  chainId: String
}
