// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export class Account {
  static entity = "Account";
  static schema = {
    id: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Registration {
  static entity = "Registration";
  static schema = {
    id: "String",
    domain: {
      id: "String",
      name: "String",
      labelName: "String",
      labelhash: "String",
      parent: "String",
      subdomains: ["String"],
      subdomainCount: "Number",
      resolvedAddress: "String",
      resolver: {
        id: "String",
        address: "String",
        addr: { id: "String" },
        contentHash: "String",
        texts: ["String"],
        coinTypes: ["Number"],
        events: [
          { id: "String", blockNumber: "Number", transactionID: "String" },
        ],
      },
      ttl: "Number",
      isMigrated: "Boolean",
      createdAt: "Number",
      owner: "String",
      registrant: "String",
      wrappedOwner: "String",
      expiryDate: "Number",
      wrappedDomain: {
        id: "String",
        expiryDate: "Number",
        fuses: "Number",
        name: "String",
      },
      events: [
        { id: "String", blockNumber: "Number", transactionID: "String" },
      ],
    },
    registrationDate: "Number",
    expiryDate: "Number",
    cost: "Number",
    registrant: { id: "String" },
    labelName: "String",
    events: [{ id: "String", blockNumber: "Number", transactionID: "String" }],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class RegistrationEvent {
  static entity = "RegistrationEvent";
  static schema = {
    id: "String",
    blockNumber: "Number",
    transactionID: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class WrappedDomain {
  static entity = "WrappedDomain";
  static schema = {
    id: "String",
    expiryDate: "Number",
    fuses: "Number",
    name: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Domain {
  static entity = "Domain";
  static schema = {
    id: "String",
    name: "String",
    labelName: "String",
    labelhash: "String",
    parent: "String",
    subdomains: ["String"],
    subdomainCount: "Number",
    resolvedAddress: "String",
    resolver: {
      id: "String",
      address: "String",
      addr: { id: "String" },
      contentHash: "String",
      texts: ["String"],
      coinTypes: ["Number"],
      events: [
        { id: "String", blockNumber: "Number", transactionID: "String" },
      ],
    },
    ttl: "Number",
    isMigrated: "Boolean",
    createdAt: "Number",
    owner: "String",
    registrant: "String",
    wrappedOwner: "String",
    expiryDate: "Number",
    wrappedDomain: {
      id: "String",
      expiryDate: "Number",
      fuses: "Number",
      name: "String",
    },
    events: [{ id: "String", blockNumber: "Number", transactionID: "String" }],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Resolver {
  static entity = "Resolver";
  static schema = {
    id: "String",
    address: "String",
    addr: { id: "String" },
    contentHash: "String",
    texts: ["String"],
    coinTypes: ["Number"],
    events: [{ id: "String", blockNumber: "Number", transactionID: "String" }],
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class ResolverEvent {
  static entity = "ResolverEvent";
  static schema = {
    id: "String",
    blockNumber: "Number",
    transactionID: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class DomainEvent {
  static entity = "DomainEvent";
  static schema = {
    id: "String",
    blockNumber: "Number",
    transactionID: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}

export class Transfer {
  static entity = "Transfer";
  static schema = {
    id: "String",
    domain: "String",
    blockNumber: "Number",
    transactionID: "String",
    owner: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "String", index: true },
  };
}
