// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class Delegation {
  static entity = "Delegation";
  static schema = {
    id: { type: "String", index: true },
    delegator: "string",
    space: "string",
    delegate: "string",
    timestamp: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Block {
  static entity = "Block";
  static schema = {
    id: { type: "String", index: true },
    number: "Number",
    timestamp: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

export class Sig {
  static entity = "Sig";
  static schema = {
    id: { type: "String", index: true },
    account: "string",
    messageHash: "string",
    timestamp: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
    instanceId: { type: "String", index: true },
  };
}

import { String, Array } from "@blockflow-labs/utils";

export interface IDelegation extends Document {
  id: String;
  delegator: string;
  space: string;
  delegate: string;
  timestamp: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface IBlock extends Document {
  id: String;
  number: Number;
  timestamp: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}

export interface ISig extends Document {
  id: String;
  account: string;
  messageHash: string;
  timestamp: string;
  blocknumber: String;
  entityId: String;
  instanceId: String;
  chainId: String;
}
