// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class CrossTransferSrc {
  static entity = "CrossTransferSrc";
  static schema = {
    id: { type: "String", index: true },
    chainId: "string",
    partnerId: "string",
    depositId: "string",
    depositor: "string",
    srcTxHash: "string",
    srcBlockNumber: "string",
    srcTokenAmount: "string",
    senderAddress: "string",
    srcTxTime: "string",
    srcTxStatus: "string",
    srcChain: "string",
    dstChain: "string",
    dstToken: "string",
    dstTokenAmount: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
  };
}

export class CrossTransferDst {
  static entity = "CrossTransferDst";
  static schema = {
    id: { type: "String", index: true },
    chainId: "string",
    depositId: "string",
    destToken: "string",
    dstAmount: "string",
    srcChain: "string",
    dstTxHash: "string",
    dstTxTime: "string",
    dstTxStatus: "boolean",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
  };
}

import { String, Array } from "@blockflow-labs/utils";

export interface ICrossTransferSrc extends Document {
  id: string; // receipt_chainId
  chainId: string;
  partnerId: string;
  depositId: string;
  depositor: string;

  srcTxHash: string;
  srcBlockNumber: string;
  srcTokenAmount: string;
  senderAddress: string;
  srcTxTime: string;
  srcTxStatus: string;
  srcChain: string;

  dstChain: string;
  dstToken: string;
  dstTokenAmount: string;
  blocknumber: String;
  entityId: String;
}

export interface ICrossTransferDst extends Document {
  id: string;
  chainId: string;

  depositId: string;
  destToken: string;
  dstAmount: string;
  srcChain: string;
  dstTxHash: string;
  dstTxTime: string;
  dstTxStatus: boolean;
  blocknumber: String;
  entityId: String;
}
