// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class PriceDB {
  static entity = "PriceDB";
  static schema = {
    id: { type: "String", index: true },
    contractAddress: "String",
    name: "String",
    symbol: "String",
    decimals: "Number",
    quote_currency: "String",
    raw_price: "String",
    price: "String",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
  };
}

export class chainlink_pair {
  static entity = "chainlink_pair";
  static schema = {
    id: { type: "String", index: true },
    update_count: "Number",
    transanction_hash: "String",
    last_block_number: "Number",
    round_id: "Number",
    impl_update: "Number",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
  };
}

import { String, Array } from "@blockflow-labs/utils";

export interface IPriceDB extends Document {
  id: String;
  contractAddress: String;
  name: String;
  symbol: String;
  decimals: Number;
  quote_currency: String;
  raw_price: String;
  price: String;
  blocknumber: String;
  entityId: String;
  chainId: String;
}

export interface Ichainlink_pair extends Document {
  id: String;
  update_count: Number;
  transanction_hash: String;
  last_block_number: Number;
  round_id: Number;
  impl_update: Number;
  blocknumber: String;
  entityId: String;
  chainId: String;
}
