// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from '@blockflow-labs/utils'

export class PriceDB {
  static entity = 'PriceDB'
  static schema = {
    id: { type: 'String', index: true },
    contractAddress: 'string',
    name: 'string',
    symbol: 'string',
    decimals: 'number',
    quoteCurrency: 'string',
    rawPrice: 'string',
    price: 'string',
    entityId: { type: 'String', index: true },
    blocknumber: { type: 'Number', index: true },
    chainId: { type: 'String', index: true },
  }
}

export class chainlink_pair {
  static entity = 'chainlink_pair'
  static schema = {
    id: { type: 'String', index: true },
    updateCount: 'number',
    transanctionHash: 'string',
    lastBlockNumber: 'number',
    roundId: 'number',
    entityId: { type: 'String', index: true },
    blocknumber: { type: 'Number', index: true },
    chainId: { type: 'String', index: true },
  }
}

import { String, Array } from '@blockflow-labs/utils'

export interface IPriceDB extends Document {
  id: string
  contractAddress: string
  name: string
  symbol: string
  decimals: number
  quoteCurrency: string
  rawPrice: string
  price: string
  blocknumber: String
  entityId: String
  chainId: String
}

export interface Ichainlink_pair extends Document {
  id: string
  updateCount: number
  transanctionHash: string
  lastBlockNumber: number
  roundId: number
  blocknumber: String
  entityId: String
  chainId: String
}
