// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class Transfer {
  static entity = "Transfer";
  static schema = {
    id: { type: "String", index: true },
    from_address: "string",
    to_address: "string",
    token_address: "string",
    token_name: "string",
    token_symbol: "string",
    raw_amount: "Number",
    raw_amount_str: "string",
    amount: "Number",
    amount_str: "string",
    usd_amount: "Number",
    usd_exchange_rate: "string",
    transfer_type: "string",
    transaction_from_address: "string",
    transaction_to_address: "string",
    transaction_hash: "string",
    log_index: "string",
    block_timestamp: "string",
    block_hash: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
  };
}

import { String, Number } from "@blockflow-labs/utils";

export interface ITransfer extends Document {
  id: String;
  from_address: string;
  to_address: string;
  token_address: string;
  token_name: string;
  token_symbol: string;
  raw_amount: Number;
  raw_amount_str: string;
  amount: Number;
  amount_str: string;
  usd_amount: Number;
  usd_exchange_rate: string;
  transfer_type: string;
  transaction_from_address: string;
  transaction_to_address: string;
  transaction_hash: string;
  log_index: string;
  block_timestamp: string;
  block_hash: string;
  blocknumber: String;
  entityId: String;
  chainId: String;
}
