// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Document } from "@blockflow-labs/utils";

export class User {
  static entity = "User";
  static schema = {
    id: { type: "String", index: true },
    balance: "string",
    txnCount: "string",
    largestTxn: "string",
    smallestTxn: "string",
    lastTxnOn: "string",
    entityId: { type: "String", index: true },
    blocknumber: { type: "Number", index: true },
    chainId: { type: "String", index: true },
  };
}

import { String } from "@blockflow-labs/utils";

export interface IUser extends Document {
  id: String;
  balance: string;
  txnCount: string;
  largestTxn: string;
  smallestTxn: string;
  lastTxnOn: string;
  blocknumber: String;
  entityId: String;
  chainId: String;
}
